id: IB446511A
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:52:46.830552
last_modified: 2023-02-08 14:52:46.830668
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: bo
bases:
  98EC:
    base_file: 98EC.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
